
---
apiVersion: v1
kind: Service
metadata:
  name: kubedoom-service
  namespace: kubedoom
spec:
  type: LoadBalancer
  ports:
    - port: 5900
      targetPort: 5900
      protocol: TCP
      name: vnc
  selector:
    app: kubedoom
